### ISSUE TITLE
*Error unpacking values in `web-platform-tests`

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wptrunner#228] opened 2017-01-19 16:49 UTC
Recent builds in the `web-platform-tests` project have been failing the "stability check" job due to an error in the invocation of `wptrunner`:

>     INFO:check_stability:Starting 10 test iterations
>     
>     Traceback (most recent call last):
>     
>       File "check_stability.py", line 726, in <module>
>         retcode = main()
>       File "check_stability.py", line 700, in main
>         wptrunner.run_tests(**kwargs)
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/wptrunner.py", line 135, in run_tests
>         **kwargs)
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/wptrunner.py", line 71, in get_loader
>         include_https=ssl_env.ssl_enabled)
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/testloader.py", line 477, in __init__
>         self._load_tests()
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/testloader.py", line 543, in _load_tests
>         for test_path, test_type, test in self.iter_tests():
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/testloader.py", line 520, in iter_tests
>         manifest_items.extend(manifest_iter)
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/testloader.py", line 437, in iterfilter
>         for item in iter:
>       File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/wptrunner/testloader.py", line 355, in __call__
>         for test_type, test_path, tests in manifest_iter:
>     ValueError: need more than 2 values to unpack

(source: https://travis-ci.org/w3c/web-platform-tests/jobs/193433989#L442)

Because the CI script fetches the latest version of `wptrunner`, and because the mentioned code path recently changed (https://github.com/w3c/wptrunner/commit/0138119c26c99989652b986b4fd92c9c1827e34a), I believe this is a problem with `wptrunner` itself.

**Comment by jgraham** [comment] 2017-01-19 16:52
Not quite. It was a problem because wpt-tools had a regression from the manifest changes, which I fixed in gecko, as I fixed some wptrunner problems with the new manifest format. I upstreamed both of these, but forgot to bump the tools submodule in wpt.

I've done that now, so if you rebase everything will work. This is annoying and would probably be fixed if we just put all these things into a monorepo so the wptrunner version matched the wpt version.

**Closed** 2017-01-19 17:46 UTC
